#!/data/data/com.termux/files/usr/bin/sh
# Post-install script for RetroArch .deb
echo "[•] You can make more requests in ig: shado_with_linux "
# Check if X11 repo exists
if [ ! -f "$PREFIX/etc/apt/sources.list.d/x11.list" ]; then
    echo "Error: X11 repository is not enabled."
    echo "Please run: pkg install x11-repo"
    echo "Installation aborted."
    exit 1
fi

# If X11 repo is present, continue normally
exit 0
